#!/bin/bash
set -e

# Include common setup
source common

# Set build dir
BUILD_DIR="${CURRENT_DIR}/tmp"

# Define function
function install_php() {
    local pkg=php-${PHP_VERSION}.tar.gz

    mkdir -p ${BUILD_DIR}
    pushd ${BUILD_DIR}

    # Get archive
    download_and_unpack ${pkg} http://www.php.net/get/${pkg}/from/us1.php.net/mirror
    pushd php-${PHP_VERSION}

    echo "Configuring PHP."

    EXTENSION_DIR=${ROOT_DIR}/ext \
    ./configure \
      --prefix=${PHP_DIR} \
      --localstatedir=${ROOT_DIR} \
      --with-mcrypt=${LIBS_DIR} \
      --enable-fpm \
      --enable-pcntl \
      --enable-mbregex \
      --enable-tokenizer=shared \
      --with-layout=PHP \
      --disable-sigchild \
      --enable-xml \
      --with-libxml-dir \
      --enable-simplexml \
      --enable-xmlreader=shared \
      --enable-dom=shared \
      --enable-filter \
      --disable-debug \
      --with-openssl \
      --with-pcre-regex \
      --with-zlib=shared \
      --enable-bcmath=shared \
      --with-bz2=shared \
      --enable-calendar=shared \
      --enable-ctype=shared \
      --with-curl=shared \
      --enable-dba=shared \
      --with-gdbm \
      --with-db4 \
      --enable-exif=shared \
      --enable-ftp=shared \
      --with-gd \
      --with-jpeg-dir \
      --with-png-dir \
      --with-zlib-dir \
      --with-xpm-dir \
      --with-freetype-dir \
      --enable-gd-native-ttf \
      --with-gettext=shared \
      --with-gmp=shared \
      --with-iconv=shared \
      --enable-mbstring \
      --enable-hash \
      --with-mysql=shared,mysqlnd \
      --with-mysqli=shared,mysqlnd \
      --enable-pdo=shared \
      --with-pdo-mysql=shared,mysqlnd \
      --with-pdo-sqlite=shared \
      --enable-shmop=shared \
      --enable-soap=shared \
      --enable-sockets \
      --with-sqlite3=shared \
      --with-regex=php \
      --enable-sysvmsg \
      --enable-sysvsem \
      --enable-sysvshm \
      --enable-wddx=shared \
      --with-xsl=shared \
      --enable-zip=shared \
      --with-tsrm-pthreads \
      --enable-intl=shared \
      --enable-opcache \
      --enable-shared=yes \
      --enable-static=no \
      --with-gnu-ld \
      --with-pic \
      --with-mhash=shared \
      --with-pgsql=shared \
      --with-pdo-pgsql=shared \
      --with-xmlrpc=shared \
      --with-readline \
      --with-kerberos=shared \
      --without-pear \
      --enable-cli \
      --enable-inline-optimization

    echo "Compiling PHP."
    make install

    echo "Cleaning build directory."
    popd
    popd
    rm -rf ${BUILD_DIR}
}

# Compile all required versions
for version in $(cat versions); do
    if [ ! -z "${version}" ]; then
        PHP_DIR="${ROOT_DIR}/php-${version}"
        PHP_VERSION="${version}"

        # Install php
        install_php

        # Remove unneeded files
        rm -f "${PHP_DIR}/bin/phar"
        rm -rf "${PHP_DIR}/etc"
        rm -rf "${PHP_DIR}/php"
        rm -rf "${PHP_DIR}/var"

        # Patch install for cartridge usage
        PHP_DIR_ESCAPED="${PHP_DIR//\//\\/}"
        LIBS_DIR_ESCAPED="${LIBS_DIR//\//\\/}"
        ROOT_DIR_ESCAPED="${ROOT_DIR//\//\\/}"

        pushd ${PHP_DIR}/bin
        for file in pecl php-config phpize; do
            if [ -f ${file} ]; then
                sed -i "s/${PHP_DIR_ESCAPED}/\${OPENSHIFT_PHP_VERSION_DIR}/g" ${file}
                sed -i "s/${LIBS_DIR_ESCAPED}/\${OPENSHIFT_PHP_LIBS_DIR}/g" ${file}
                sed -i "s/${ROOT_DIR_ESCAPED}/\${OPENSHIFT_PHP_DIR}/g" ${file}
            fi
        done
        popd

        pushd ${PHP_DIR}/include/php/main
        file=build-defs.h
        if [ -f ${file} ]; then
            sed -i "s/${PHP_DIR_ESCAPED}/\${OPENSHIFT_PHP_VERSION_DIR}/g" ${file}
            sed -i "s/${LIBS_DIR_ESCAPED}/\${OPENSHIFT_PHP_LIBS_DIR}/g" ${file}
            sed -i "s/${ROOT_DIR_ESCAPED}/\${OPENSHIFT_PHP_DIR}/g" ${file}
        fi
        popd


        # Compress
        pushd ${ROOT_DIR}
        cp -R ext php-${version}/
        tar -zcvf "${OPENSHIFT_REPO_DIR}/public/php-${version}.tar.gz" php-${version}
        popd

        # Clean up
        rm -rf ${PHP_DIR}
    fi
done
